
FROM node:22-alpine

WORKDIR /app

# --- COMENTE ESTAS LINHAS TEMPORARIAMENTE ---
# COPY package*.json ./
# RUN npm install 
# --------------------------------------------

EXPOSE 3000

# Inicia em modo de desenvolvimento
CMD ["npm", "run", "dev"]